# Generated by Django 6.0.3 on 2026-03-16 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('ME', 'Mechanical'), ('CE', 'Civil')], max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('faculty_approved', 'Faculty Approved'), ('dept_head_approved', 'Department Head Approved'), ('hod_approved', 'HOD Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventcoordinator',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventcoordinator',
            name='role',
            field=models.CharField(choices=[('student_coord', 'Student Coordinator'), ('sub_coord', 'Sub Coordinator'), ('volunteer', 'Volunteer')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='eventcoordinator',
            unique_together={('event', 'student')},
        ),
    ]
