# Generated by Django 6.0.3 on 2026-03-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_department_alter_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='proposal_pdf',
            field=models.FileField(blank=True, null=True, upload_to='event_proposals/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('ME', 'Mechanical'), ('CE', 'Civil'), ('AIML', 'AI & ML')], max_length=10),
        ),
    ]
